version: '3.3'
services:
  orai:
    image: orai/orai:alpine-wasm
    working_dir: /workspace
    tty: true    
    ports:
      - 1319:1317
      - 26666:26656
      - 26667:26657
    env_file:
      - orai.dev.env
    volumes:
      - ./:/workspace
      - ./smart-contracts:/workspace/oraiwasm