version: '3.3'
services:
  orai:
    image: orai/orai:alpine-thesis
    working_dir: /workspace
    tty: true    
    ports:
      - 1319:1317
      - 26666:26656
      - 26667:26657
    env_file:
      - orai.env
    volumes:
      - ./:/workspace
      - $HOME/bkc_research/cosmos/oraiwasm/package:/workspace/smart-contracts