version: '3.3'
services:
  node1:
    image: orai/orai:alpine
    working_dir: /workspace/swarm/node1
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    security_opt:
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    environment:
      ###################### basic information for a node
      # account name, can be anything
      - USER=duc
      # the mnemonic of your account. You should keep this in secret only, and remember to put it in the double quote "", otherwise it will not work
      - MNEMONIC=flight stage identify gentle earn scrub ski minute slide butter dignity crisp curtain confirm brand rate turkey social pattern mind awkward decide pet oven
      # Passphrase for your keyring. Keep this safe and secure.
      - PASS=foo
      # the moniker of your node
      - MONIKER=ducphamle
      ###################### basic information to become a validator
      # the amount of tokens you want to stake into the validator
      - AMOUNT=10000orai
      # the commission rate between the delegators and the validator
      - COMMISSION_RATE=0.10
      # the maximum comission rate allowed
      - COMMISSION_MAX_RATE=0.20
      # the maximum changes in the commission rate
      - COMMISSION_MAX_CHANGE_RATE=0.01
      # the minimum number of tokens you must delegate into your validator.
      - MIN_SELF_DELEGATION=100
      # how gas is calculated, default is auto to reduce overhead
      - GAS=auto
      # the gas price required that the users have to pay when using your validator.
      - GAS_ADJUSTMENT=1.15
      # your security contract information (optional)
      - GAS_PRICES=0.025orai
      # your security contact (optional)
      - SECURITY_CONTRACT=efg
      # your node identity (optional)
      - IDENTITY=node1
      # your website (optional)
      - WEBSITE=xyx.com
      # details about your validator (optional)
      - DETAILS=helloworld
      - PERSISTENT_PEERS=64f3a86205af19151b8d74ce4c11fc54f55429c3@node2:26656,beef99b0dff99331ffe39a75b44648bfa99c31f2@node3:26656

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/share/orai:/workspace
      - /opt/share/orai/fn_dev.sh:/usr/local/bin/fn
    command: fn start
    # - bash -c "fn init && fn createValidator && fn start"

  node2:
    image: orai/orai:alpine
    working_dir: /workspace/swarm/node2
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    security_opt:
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    environment:
      ###################### basic information for a node
      # account name, can be anything
      - USER=duc
      # the mnemonic of your account. You should keep this in secret only, and remember to put it in the double quote "", otherwise it will not work
      - MNEMONIC=flight stage identify gentle earn scrub ski minute slide butter dignity crisp curtain confirm brand rate turkey social pattern mind awkward decide pet oven
      # Passphrase for your keyring. Keep this safe and secure.
      - PASS=foo
      # the moniker of your node
      - MONIKER=ducphamle
      ###################### basic information to become a validator
      # the amount of tokens you want to stake into the validator
      - AMOUNT=10000orai
      # the commission rate between the delegators and the validator
      - COMMISSION_RATE=0.10
      # the maximum comission rate allowed
      - COMMISSION_MAX_RATE=0.20
      # the maximum changes in the commission rate
      - COMMISSION_MAX_CHANGE_RATE=0.01
      # the minimum number of tokens you must delegate into your validator.
      - MIN_SELF_DELEGATION=100
      # how gas is calculated, default is auto to reduce overhead
      - GAS=auto
      # the gas price required that the users have to pay when using your validator.
      - GAS_ADJUSTMENT=1.15
      # your security contract information (optional)
      - GAS_PRICES=0.025orai
      # your security contact (optional)
      - SECURITY_CONTRACT=efg
      # your node identity (optional)
      - IDENTITY=node2
      # your website (optional)
      - WEBSITE=xyx.com
      # details about your validator (optional)
      - DETAILS=helloworld
      - PERSISTENT_PEERS=c691546c18abf62a37128e3cd5f879c0a56e97a8@node1:26656,beef99b0dff99331ffe39a75b44648bfa99c31f2@node3:26656

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/share/orai:/workspace
      - /opt/share/orai/fn_dev.sh:/usr/local/bin/fn
    command: fn start
    # - bash -c "fn init && fn createValidator && fn start"

  node3:
    image: orai/orai:alpine
    working_dir: /workspace/swarm/node3
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    security_opt:
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    environment:
      ###################### basic information for a node
      # account name, can be anything
      - USER=duc
      # the mnemonic of your account. You should keep this in secret only, and remember to put it in the double quote "", otherwise it will not work
      - MNEMONIC=flight stage identify gentle earn scrub ski minute slide butter dignity crisp curtain confirm brand rate turkey social pattern mind awkward decide pet oven
      # Passphrase for your keyring. Keep this safe and secure.
      - PASS=foo
      # the moniker of your node
      - MONIKER=ducphamle
      ###################### basic information to become a validator
      # the amount of tokens you want to stake into the validator
      - AMOUNT=10000orai
      # the commission rate between the delegators and the validator
      - COMMISSION_RATE=0.10
      # the maximum comission rate allowed
      - COMMISSION_MAX_RATE=0.20
      # the maximum changes in the commission rate
      - COMMISSION_MAX_CHANGE_RATE=0.01
      # the minimum number of tokens you must delegate into your validator.
      - MIN_SELF_DELEGATION=100
      # how gas is calculated, default is auto to reduce overhead
      - GAS=auto
      # the gas price required that the users have to pay when using your validator.
      - GAS_ADJUSTMENT=1.15
      # your security contract information (optional)
      - GAS_PRICES=0.025orai
      # your security contact (optional)
      - SECURITY_CONTRACT=efg
      # your node identity (optional)
      - IDENTITY=node3
      # your website (optional)
      - WEBSITE=xyx.com
      # details about your validator (optional)
      - DETAILS=helloworld
      - PERSISTENT_PEERS=c691546c18abf62a37128e3cd5f879c0a56e97a8@node1:26656,64f3a86205af19151b8d74ce4c11fc54f55429c3@node2:26656

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/share/orai:/workspace
      - /opt/share/orai/fn_dev.sh:/usr/local/bin/fn
    command: fn start
    # - bash -c "fn init && fn createValidator && fn start"

networks:
  net:
    external:
      name: orai_net
